### ISSUE TITLE
rscript fails in batch mode on Stata for Windows

### ISSUE THREAD

**Issue by davidmolitor** [reifjulian/rscript#2]
Calling `rscript` when running Stata for Windows in batch mode generates the following error:

"request ignored because of batch mode"

**Comment by davidmolitor** [comment]
This appears to be an issue with the Stata `shell` command, not `rscript`. Stata `shell` command is disabled on Windows when running in batch mode. 

See related discussion at [https://www.statalist.org/forums/forum/general-stata-discussion/general/1365964-shell-commands-in-batch-mode](https://www.statalist.org/forums/forum/general-stata-discussion/general/1365964-shell-commands-in-batch-mode)

This closes #2

**Comment by mcaceresb** [comment]
I recently run into this issue. I don't think this is a widely known idiosyncrasy so It'd be helpful if there was a note about this somewhere in the README or the help file.

**Comment by davidmolitor** [comment]
The `rscript` update to version 1.1 (https://github.com/reifjulian/rscript/commit/a01d073f96928080eea95691a279d64c63aec67a) now breaks gracefully and issues an informative error message when running in batch mode on Windows.

Regarding the underlying limitation that Stata will ignore shell commands in batch mode on Windows, here is the explanation and suggested workaround I received from Stata's technical support team.

> From: Stata Technical Services
> Date: 2021-08-03 
> Subject: shell in batch mode on Windows
> 
> For a variety of reasons associated with the behavior of Windows and other
> applications, we have this function turned off when in batch mode.  It could
> be considered "dangerous" to shell out of Stata to another application not
> knowing how or if the other application will return.
> 
> Instead of running Stata in batch mode you can run it minimized by including
> the line -window manage minimize- at the start of the do-file. You can even
> launch it from the command prompt with a command like the following:
> 
>  StataMP-64.exe do batchfile.do
> 
> If you start the do-file with:
> 
>  window manage minimize
>  log using newlog
> 
> end and it with:
> 
>  log close
>  exit, clear STATA
> 
> Then Stata will allow you to shell out and will automatically exit similar to
> running in batch mode.
