### ISSUE TITLE
async option

### ISSUE THREAD

**Issue by reifjulian** [reifjulian/rscript#6]
@davidmolitor: I added code to `rscript` (see branch ["development"](https://github.com/reifjulian/rscript/tree/development) ) that incorporates two changes:

1. I added an `async` option. This could be useful when running a lot of R scripts in parallel in the background. The code has been tested on Windows, Unix, and Mac OS. I added an `async` example to `/test/examples.do` and updated the help file.

2. When running `/test/examples.do` I encountered a bug. The newest version of `tidyverse` now has the following warning message when you load it: `"Use the conflicted package to force all conflicts to become errors"` We had previously coded `rscript` to break if it found the string `error` in the stderr file, so the master version of `rscript` currently breaks for anybody using recent versions of `tidyverse`. (This break could be overridden by specifying the option `force`.) I have adjusted our code to instead search for the case-insensitive string `error:` (colon  added). We could strengthen this to search for the (case-sensitive) string `Error:` if we think that's better. It's unclear to me if R has a maintained standard for how to report genuine errors, as opposed to just warnings, in the stderr output.

When you get a chance, let me know if you have any thoughts on these changes, and if you have any issues running `/test/examples.do`

**Comment by davidmolitor** [comment]
Regarding catching errors, per http://adv-r.had.co.nz/Exceptions-Debugging.html

> errors always start with “Error” and warnings with “Warning message”

In fact, I think you can define errors to be flagged by the case-sensitive string "Error: " at the start of a new line. This appears to be true as long as error messages are produced by the [`stop`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/stop) command. I'm unaware of error messages being produced any other way.

However, one situation in which stopping code on detection of "Error: " could be a problem is if the user is using [`try`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/try.html) to handle error recovery. From the documentation, it sounds like `try` prints any error messages it catches to the stderr connection. In this case, the user may need to specify the `force` option when calling `rscript`.

**Comment by reifjulian** [comment]
Ok, I incorporated your suggestion into the development branch. We were also forcing a break previously if stderr contained the case-insensitive string "error ", which I have now removed. To recap, `rscript` will now break if and only if stderr contains the case-sensitive string "Error: ".

Re: `try`, users also have an option to redirect that output to stdout, which would avoid the issue you mention.

**Comment by davidmolitor** [comment]
I pulled the changes to `rscript` and ran `examples.do` on my Windows machine. It ran successfully, but it flagged as an error any message in stderr that contained the string "Error:", not just lines that began with that string.

So I changed line 422 of `rscript.ado` as follows (see diff at https://github.com/reifjulian/rscript/commit/5c6b3a57f1474e00147ce6a588ef669819f91759):

```
# Previous code
if (strpos(line, "Error: ")!=0) exit(error(198))

# New code
if (strpos(line, "Error: ")==1) exit(error(198))
```

I also added a series of new tests to `examples.do` to confirm that only stderr lines beginning with case-sensitive "Error:" would get flagged as an error. Note that for some reason, it doesn't need a trailing space to get flagged.

https://github.com/reifjulian/rscript/blob/5c6b3a57f1474e00147ce6a588ef669819f91759/test/examples.do#L87-L93

Are these changes in line with the behavior you were aiming for with the error handling?

**Comment by reifjulian** [comment]
Given the link above stating that `errors always start with “Error”`, I think the change you made is sensible.

It appears that R outputs an extra space to the warning message in stderr. I replicated this behavior in RStudio (see image below). If we think that behavior might change in the future or differ across OS, then we should further tighten the criteria from "Error: " to "Error:". Because your most recent change now requires "Error" to be the first word found in stderr, I think changing it from `"Error: "` to `"Error:"` would be ok. Thoughts?

![image](https://user-images.githubusercontent.com/42722121/234020438-8f52aad4-cde0-488e-9d87-8952cd0609d0.png)

**Comment by davidmolitor** [comment]
I agree that changing the error detection criteria from "Error: " to "Error:" would be ok.

**Comment by reifjulian** [comment]
I made the change, confirmed the QC script runs on my windows machine, and committed the change to the development branch.

If you have any thoughts on the `async` option, let me know. Otherwise I'll plan to push this development version to the master branch in the next week or two.

**Comment by davidmolitor** [comment]
Sounds good to me.

**Comment by reifjulian** [comment]
The new `async` option appears to no longer work on Windows in Stata 18. I sent an email to tech support.

Minimum working example (Windows only), freezes Stata 18 but not Stata 17:
```stata
shell start /B /MIN "" "C:\WINDOWS\system32\notepad.exe"
```

**Comment by reifjulian** [comment]
Stata confirmed that they changed up behavior of `shell` in Stata 18. In fact, the Stata 17 behavior was a bug: `shell` is supposed to freeze on windows; switching to `winexec` resolves the issue. I have updated `rscript` accordingly.

**Comment by davidmolitor** [comment]
Just to confirm, `shell` still works on Stata 18 for Windows for synchronous calls, just not for asynchronous ones? I think the following lines are the ones you changed, and that `shell` is still used for synchronous calls:

https://github.com/reifjulian/rscript/blob/16846587ed7391f7fb51ce0f71b50e51073fd241/src/rscript.ado#L269-L272

Should we instead use `winexec` for all Windows calls, and would doing so solve the limitation that `rscript does not work in batch mode on Stata for Windows because Stata ignores shell requests (as of Stata 17.0)`?

https://github.com/reifjulian/rscript/blob/16846587ed7391f7fb51ce0f71b50e51073fd241/src/rscript.ado#L22-L26

**Comment by reifjulian** [comment]
Yes, `shell` still works fine for synchronous calls. The new code uses `winexec` only for asynchronous calls. I don't think `winexec` can help with batch mode for synchronous calls; I have not tested to see whether windows batch mode works with asynchronous calls.

Implementing the new `async` option uncovered a subtle bug. Typically, `echo "$0"` on ubuntu returns `#!/bin/bash`. However, when injecting a script as User Data on an aws instance running ubuntu, `echo "$0"` will instead return `#!/bin/sh`. (I suspect this may also occur if logged in as root instead of as a normal user, but I have not verified that. Also see additional explanation [here](https://askubuntu.com/questions/141928/what-is-the-difference-between-bin-sh-and-bin-bash).) This bug caused `rscript` to think it is running on windows when in fact it was unix, and if the user specified the `async` option then `rscript` incorrectly uses `winexec`, which does nothing on unix. I fixed the bug by adding an additional `else` statement that uses the bash syntax for any unix/mac os that is not flagged as using csh or bash shell by `rscript`:

https://github.com/reifjulian/rscript/blob/868a324118d5a8e0851c3e81ed3ba7c26dbe5aab/src/rscript.ado#LL271C1-L274C4

**Comment by reifjulian** [comment]
I've pushed these changes to the master branch. Version number is now 1.1.1.
