### ISSUE TITLE
Bug when running R on non-English installations

### ISSUE THREAD

**Issue by reifjulian** [reifjulian/rscript#8]
Some of the error-checking functions, such as `parse_stderr_version_control()`, identify errors by checking for the string "error" in the stderr file. However, this word may not appear when running R with non-English settings.

Possible solutions (at least for the version control portion of `rscript`): 
  - use `LANGUAGE=en` as a command-line option
  - In the R script that checks version and package requirements, add `Sys.setenv(LANGUAGE="en")`

**Comment by davidmolitor** [comment]
One other possible solution:
- Allow the user to specify keywords (e.g., "erreur" or "fehler") that the error-checking functions will use to check for errors

**Comment by reifjulian** [comment]
The command `Sys.setenv(LANGUAGE="en")` doesn't work for me on RStudio windows. For example, the following code produces identical error messages:
```{r}
Sys.setenv(LANGUAGE="en")
x+2
Sys.setenv(LANGUAGE="fr")
x+2
```

However, the command line option `LANGUAGE=en` works, at least on Windows. (Have not tested Mac OS or Unix.) I pushed a bug fix to the development branch. Note that this fix only addresses the bug for the `rversion()` and `require()` options. We probably shouldn't pass this option when running the user's script, since we can't know how or whether the script is parsing options.

**Comment by davidmolitor** [comment]
Here is what I get on RStudio Windows (R version 4.3.1, RStudio 2023.09.0). Do you get something different?

![image](https://github.com/reifjulian/rscript/assets/10534077/672cbaa5-2591-46a5-9614-0e98e9fa3a93)

**Comment by reifjulian** [comment]
Yes. I am running R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"

![image](https://github.com/reifjulian/rscript/assets/42722121/a19af90d-24b5-46e5-a30e-413f21f30c51)

**Comment by davidmolitor** [comment]
Perhaps you are missing the necessary translation catalogue. 

From [R: Environment Variables](https://stat.ethz.ch/R-manual/R-devel/library/base/html/EnvVar.html):
> LANGUAGE:
> Optional. The language(s) to be used for message translations. This is consulted when needed.

From [Translating R Messages, R >= 3.0.0](https://developer.r-project.org/Translations30.html):
> If no suitable translation catalogue is found or a particular message is not translated in the selected catalogue, English is used.

The information here suggests that `Sys.setenv(LANGUAGE="en")` may always work to change the language to English, but it might fail to translate messages to other languages. This is consistent with `Sys.setenv(LANGUAGE="fr")` not working for you.

> We probably shouldn't pass this option when running the user's script, since we can't know how or whether the script is parsing options.

I agree

**Comment by reifjulian** [comment]
Agreed that is what may be happening, although I find the documentation a bit unclear. Some of the parameters are also taken from the [locale](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/locales). 

Some of these issues may be OS-specific, which calls for taking care.

**Comment by davidmolitor** [comment]
When running an R script using `rscript` on the command line, is setting `LANGUAGE=en` as a command line option different from having `Sys.setenv(LANGUAGE="en")` in the script itself?

ChatGPT suggests the answer is yes, and that it is "more reliable to set the LANGUAGE=en at the command line":


Setting LANGUAGE=en on the command line before running an Rscript command and calling Sys.setenv(LANGUAGE="en") within the R script can have similar effects, but they operate at different stages of the R session:

1.	Command Line: Setting LANGUAGE=en as part of the command line invocation sets the environment variable for the R session before it starts. This means that the language setting is applied from the very beginning of the R session, influencing all subsequent operations, including the loading of packages, which might have language-dependent behavior.

   Example:

   ```
   LANGUAGE=en Rscript script.R
   ```


2.	Inside R Script: Calling Sys.setenv(LANGUAGE="en") within the R script sets the environment variable after the R session has already started. This will affect all operations that occur after this line is executed. However, any package loading or functions that rely on the locale settings before this line will not be affected.

   Example within script.R:

   ```
   Sys.setenv(LANGUAGE="en")
   ```



It’s generally more reliable to set the LANGUAGE=en at the command line if you want to ensure that all parts of the script, including the startup behavior and package messages, are in English. If you set it within the script, it may not affect messages that occur before the Sys.setenv() call.

**Comment by davidmolitor** [comment]
ChatGPT also says that in a Unix-like command line, `LANGUAGE=en` should come before the `rscript` command, as in

```
LANGUAGE=en Rscript script.R
```

In the development version, `LANGUAGE=en` comes after `rscript` 
https://github.com/reifjulian/rscript/commit/a115c65b3041722508e27e6e7cd0cd499747dfb6

ChatGPT says:

> If you write `Rscript script.R LANGUAGE=en` at the command line, the `LANGUAGE=en` part is interpreted as an argument to the script rather than setting an environment variable for the R session. In this case, `LANGUAGE=en` is passed to `script.R` as a command-line argument, which the script would need to handle explicitly, typically using command-line argument parsing functions like `commandArgs()`.
> 
> The script would not automatically recognize this as a language setting; you would need to have something in your R script that processes this argument and sets the language environment accordingly. If you want to set the language environment for the R session itself, the `LANGUAGE=en` part must precede the `Rscript` command.

Here's a test: does `LANGUAGE=fr` cause errors to display in French? I'm on a plane now, but can test later.

**Comment by reifjulian** [comment]
This accords with our experience so far. Two more thoughts:

1. For redundancy, we might want to add `Sys.setenv(LANGUAGE="en")` to our version control script. It shouldn't hurt, right?
2. I was unable to get other ordering for `LANGUAGE=en` to work on Windows command line. It can work if you do it separately on two lines, eg
```
set language=fr
"C:/Program Files/R/R-4.3.1/bin/Rscript.exe" "C:\Users\jreif\Dropbox/test.R"
```

However, in a (non-interactive) Stata script I believe you can only run single-line shell calls. ChatGPT suggested the following code would work for "chaining" a multi-line command into a single line:
```stata
shell set language=fr & "`rpath'" "$DROPBOX/test.R"
```
This code runs for me, but it does not correctly set the language to French. 

If you have any success, let me know. I agree this would be a better method if we can get it to work.

**Comment by davidmolitor** [comment]
On Windows, I confirmed that the following code based on [your example](https://github.com/reifjulian/rscript/issues/8#issuecomment-1892412728) outputs error messages in English, not French.

```
shell set LANGUAGE=fr & "`rpath'" "$Dropbox/gives_error.R" > `out' 2>`err'
```

However, the following modification—wrapping `LANGUAGE=fr` in quotes—works for me, outputting the error message in French.
```
shell set "LANGUAGE=fr" & "`rpath'" "$Dropbox/gives_error.R" > `out' 2>`err'
```

Does this work for you? We could add `Sys.setenv(LANGUAGE="en")` as redundancy, but I'd prefer to avoid that unless there is a known benefit because redundancies can make it harder to debug code down the line.

**Comment by reifjulian** [comment]
Excellent, that seems to work! I reverted the `development` branch back to master, and then made the command-line changes for the shell calls, for BOTH the version control script and the user script. We will need to test these before pushing to master. Doing so is a bit complicated, here are my suggestions:

1. Test out the version control code, separately for csh, bash, other unix, and windows systems if possible. Do so as follows: 
    - Confirm that `rscript, rversion(1.5 1.5)` produces usual English-language error
    - Go into `/src/rscript.ado`, and change `LANGUAGE=en` to `LANGUAGE=fr`. Confirm the error output changes language
2. Create a new test.R script that produces an error
    - Confirm that running it via `rscript` produces the usual error (+ break)
    - Go into `rscript.ado`, and change `LANGUAGE=en` to `LANGUAGE=fr`. Confirm the error output changes
      - Note: on windows, this needs to be tested separately for the `async` and `sync` options (the former uses `winexec` rather than `shell`, which is a very different syntax)

I have so far confirmed (1) above, for Windows.

Thoughts?

**Comment by reifjulian** [comment]
I was unable to get this fix to work on linux with tcsh shell (used by NBER servers). Here's how to replicate the problem. Navigate to the `rscript/test` directory in Stata for Unix on the NBER servers. The following code will give you the typical expected output:

```stata
tempfile t1
tempfile t2
cap erase `t1'
cap erase `t2'
shell ("/usr/bin/Rscript" "example_1.R" "arg1 with spaces" "/tmp/St3211844.000002" > `t1') >& `t2'
type `t1'
type `t2'
```

I confirmed that the following csh code runs as expected in the tcsh shell:
```csh
setenv LANGUAGE en ; /usr/bin/Rscript "example_1.R" "arg1 with spaces"
setenv LANGUAGE fr ; /usr/bin/Rscript "example_1.R" "arg1 with spaces"
```

However I haven't been able to make it work via the Stata call:
```stata
tempfile t1
tempfile t2
cap erase `t1'
cap erase `t2'
shell ("setenv LANGUAGE en ;" "/usr/bin/Rscript" "example_1.R" "arg1 with spaces" "/tmp/St3211844.000002" > `t1') >& `t2'
type `t1'
type `t2'
```

I tried some other variations (eg, using multiple parentheses) but had no luck. Let me know if you can get it to work. If not, our second-best option is to just rely on `Sys.setenv(LANGUAGE="en")`, which does have the advantage of not introducing unexpected bugs in different OS's via this complicated change to the shell call.

**Comment by davidmolitor** [comment]
I'm not sure I follow what output you are expecting from each chunk. The first runs without error for me on the NBER server (as I believe it should) whereas the csh code in the second chunk produces errors.

If the goal of the last chunk is to set the language for error messages, I think you just need to remove the quotes around `setenv LANGUAGE en` and also change the arguments fed to `example_1.R` to produce an error. See below.

```
. tempfile t1
. tempfile t2

* ************************************
* 1. example_1.R runs without error
* ************************************
. cap erase `t1'
. cap erase `t2'
. shell (setenv LANGUAGE fr; "/usr/bin/Rscript" "example_1.R" "arg1 with spaces" "/tmp/St3211844.000002" > `t1') >& `t2'
. type `t1'
[1] "arg1 with spaces"
[1] "/tmp/St3211844.000002"

. type `t2'

. type "/tmp/St3211844.000002"
"","V1","V2","V3","V4","V5"
"1",1,3,5,7,9
"2",2,4,6,8,10

* ************************************
* 2. example_1.R returns an error in French
* ************************************
. cap erase `t1'
. cap erase `t2'
. shell (setenv LANGUAGE fr; "/usr/bin/Rscript" "example_1.R" "arg1 with spaces" > `t1') >& `t2'
. type `t1'
[1] "arg1 with spaces"
[1] NA

. type `t2'
Erreur dans if (file == "") file <- stdout() else if (is.character(file)) { :
  valeur manquante là où TRUE / FALSE est requis
Appels : write.csv -> eval.parent -> eval -> eval -> <Anonymous>
Exécution arrêtée

* ************************************
* 2. example_1.R returns an error in English
* ************************************
. cap erase `t1'
. cap erase `t2'
. shell (setenv LANGUAGE en; "/usr/bin/Rscript" "example_1.R" "arg1 with spaces" > `t1') >& `t2'
. type `t1'
[1] "arg1 with spaces"
[1] NA

. type `t2'
Error in if (file == "") file <- stdout() else if (is.character(file)) { :
  missing value where TRUE/FALSE needed
Calls: write.csv -> eval.parent -> eval -> eval -> <Anonymous>
Execution halted
```

**Comment by reifjulian** [comment]
Thanks, that works. I must not have tried the combination without the double quotes! I have updated development version of `rscript.ado` to use `setenv LANGUAGE en;` instead of `"LANGUAGE=en"` for tcsh shell.

- rscript 1.1.2 4feb2024 confirmed on MacOS (bash shell)
- rscript 1.1.2 4feb2024 confirmed on NBER servers (tcsh shell)
- rscript 1.1.2 4feb2024 confirmed on Windows (including `async`)
- rscript 1.1.2 4feb2024 confirmed on ubuntu (bash shell)

**Comment by reifjulian** [comment]
This has been pushed to master as version 1.1.2 4feb2024.
